spring:
  application:
    name: user-service
server:
  port: 8080
  forward-headers-strategy: framework
firebase:
  storage:
    bucketName: "ctu-nss.appspot.com"
  firestore:
    collections:
      resident: residents
      service: services
      employee: employees
      department: departments
      analyst: analysts
  service:
    account:
      file: "keys/firebase-service-account-key.json"