spring:
  application:
    name: user-service
server:
  port: 8080
  forward-headers-strategy: framework
resident:
  collection:
    name: residents
service:
  collection:
    name: services
employee:
  collection:
    name: employees
departments:
  collection:
    name: departments
analysts:
  collection:
    name: analysts