name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_ZONE: europe-central2
  GAR_REPOSITORY: better-city
  IMAGE_NAME: user-service
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker $GAR_ZONE-docker.pkg.dev --quiet

      - name: Build and Push JIB image
        run: |-
          ./mvnw compile jib:build -Djib.to.image=$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME:latest -Djib.container.environment=SPRING_PROFILES_ACTIVE=production -DskipTests=true