name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_ZONE: europe-central2
  GAR_REPOSITORY: better-city
  IMAGE_NAME: user-service
  CLUSTER_NAME: better-city-1
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Google Cloud Get Credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'better-city-1'
          location: 'europe-central2'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker $GAR_ZONE-docker.pkg.dev --quiet

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Push JIB image
        run: |-
          mvn compile jib:build -Djib.to.image=$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME:latest -Djib.container.environment=SPRING_PROFILES_ACTIVE=production -DskipTests=true
          echo "DOCKER_IMAGE_HASH=$(cat target/jib-image.digest)" >> $GITHUB_ENV

      - name: Update GKE Deployment
        run: |-
          kubectl set image deployment/$IMAGE_NAME $IMAGE_NAME=$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPOSITORY/$IMAGE_NAME@$DOCKER_IMAGE_HASH